import type { MapDefinition } from '../../game/types.ts'

export const forestValleyMap: MapDefinition = {
  id: 'forest-valley',
  name: 'Forest Valley',
  description: 'A small combat test valley with one enemy outpost.',
  size: {
    width: 320,
    height: 320,
  },
  playerSpawn: {
    position: { x: 0, y: -120 },
    facing: 0,
  },
  terrain: {
    type: 'grass',
    groundTexture: 'forest-ground',
    ambientColor: 0xaed6a1,
    fogColor: 0xcde5be,
    fogNear: 120,
    fogFar: 320,
  },
  ambience: {
    skyTint: 0xcfe8ff,
    lightDirection: [90, 150, 60],
  },
  spawns: [
    {
      kind: 'forest-cluster',
      center: { x: -90, y: -20 },
      radius: 76,
      density: 0.0072,
      variants: ['Tree_1_B_Color1', 'Tree_2_A_Color1', 'Tree_3_A_Color1', 'Tree_4_B_Color1'],
    },
    {
      kind: 'forest-cluster',
      center: { x: -32, y: 48 },
      radius: 58,
      density: 0.0058,
      variants: ['Tree_1_B_Color1', 'Tree_2_A_Color1', 'Tree_3_A_Color1', 'Tree_4_B_Color1'],
    },
    {
      kind: 'forest-cluster',
      center: { x: 90, y: -60 },
      radius: 54,
      density: 0.0052,
      variants: ['Tree_1_B_Color1', 'Tree_2_A_Color1', 'Tree_4_B_Color1'],
    },
    {
      kind: 'forest-cluster',
      center: { x: 60, y: 112 },
      radius: 52,
      density: 0.005,
      variants: ['Tree_2_A_Color1', 'Tree_3_A_Color1', 'Tree_4_B_Color1'],
    },
    {
      kind: 'forest-cluster',
      center: { x: -118, y: 92 },
      radius: 44,
      density: 0.0048,
      variants: ['Tree_1_B_Color1', 'Tree_3_A_Color1'],
    },
    {
      kind: 'forest-cluster',
      center: { x: 128, y: 14 },
      radius: 36,
      density: 0.0045,
      variants: ['Tree_1_B_Color1', 'Tree_2_A_Color1', 'Tree_4_B_Color1'],
    },
    {
      kind: 'base',
      center: { x: 52, y: -6 },
      buildingCount: 10,
      turretCount: 0,
      launcherCount: 0,
      difficulty: 1,
      structureVariants: ['barracks', 'watchtower', 'market', 'temple'],
    },
    {
      kind: 'base',
      center: { x: 110, y: 72 },
      buildingCount: 12,
      turretCount: 0,
      launcherCount: 0,
      difficulty: 2,
      structureVariants: ['barracks', 'watchtower', 'storage', 'temple', 'towncenter'],
    },
    {
      kind: 'base',
      center: { x: -75, y: 78 },
      buildingCount: 9,
      turretCount: 0,
      launcherCount: 0,
      difficulty: 2,
      structureVariants: ['watchtower', 'storage', 'market', 'temple'],
    },
    {
      kind: 'base',
      center: { x: -128, y: -52 },
      buildingCount: 7,
      turretCount: 0,
      launcherCount: 0,
      difficulty: 1,
      structureVariants: ['barracks', 'watchtower', 'market', 'storage'],
    },
  ],
}
